-- 테이블 제거
DROP TABLE ORDERDETAILS;
DROP TABLE ORDERS;
DROP TABLE CART;
DROP TABLE MEMBER;
DROP TABLE PRODUCT;

-- 테이블 생성
-- 제품 정보
CREATE TABLE PRODUCT(
    pCODE       VARCHAR2(4)     PRIMARY KEY,
    pNAME       VARCHAR2(60)    NOT NULL,
    PRICE       NUMBER(5)       NOT NULL,
    pINVEN      NUMBER(3)       DEFAULT 0
);
SELECT * FROM PRODUCT;
DESC PRODUCT;

-- 회원 정보
CREATE TABLE MEMBER (
    mCOUNT      NUMBER(5)       NOT NULL,
    mID         VARCHAR2(8)     PRIMARY KEY,
    mNAME       VARCHAR2(21)    NOT NULL,
    mADDRESS    VARCHAR2(60)    NOT NULL UNIQUE,
    mMAIL       VARCHAR2(60)    NOT NULL UNIQUE,
    mTEL        VARCHAR2(13)    NOT NULL UNIQUE
);
SELECT * FROM MEMBER;
DESC MEMBER;

-- 장바구니
CREATE TABLE CART (
    cNO         NUMBER(4)       PRIMARY KEY,
    mID         VARCHAR2(8)     NOT NULL,
    pCODE       VARCHAR2(4)     NOT NULL,
    QTY         NUMBER(3)       NOT NULL,
    COST        NUMBER(7)       NOT NULL,
    FOREIGN KEY (mID) REFERENCES MEMBER(mID),
    FOREIGN KEY (pCODE) REFERENCES PRODUCT(pCODE)
);
SELECT * FROM CART;
DESC CART;

-- 주문
CREATE TABLE ORDERS (
    oCODE       VARCHAR2(30)    PRIMARY KEY,
    mID         VARCHAR2(8)     NOT NULL,
    oDATE       VARCHAR2(19)    DEFAULT TO_CHAR(SYSDATE, 'YYYY"년" MM"월" DD"일"'),
    oNAME       VARCHAR2(21)    NOT NULL,
    oADDRESS    VARCHAR2(60)    NOT NULL,
    oTEL        VARCHAR2(13)    NOT NULL,   
    FOREIGN KEY (mID) REFERENCES MEMBER(mID)    
);
SELECT * FROM ORDERS;
DESC    ORDERS;

-- 주문 상세
CREATE TABLE ORDERDETAILS (
    odNO        NUMBER(4)       PRIMARY KEY,
    oCODE       VARCHAR(10),
    pCODE       VARCHAR2(4)     NOT NULL,
    PRICE       NUMBER(5)       NOT NULL,
    pQTY        NUMBER(3)       NOT NULL,
    FOREIGN KEY (oCODE) REFERENCES ORDERS(oCODE),
    FOREIGN KEY (pCODE) REFERENCES PRODUCT(pCODE)    
);
SELECT * FROM ORDERDETAILS;
DESC ORDERDETAILS;

-- DB입력
-- PRODUCT
DELETE FROM PRODUCT;
INSERT INTO PRODUCT VALUES('A1', '맥주', 3000, 100);
INSERT INTO PRODUCT VALUES('B1', '땅콩', 3000, 100);
INSERT INTO PRODUCT VALUES('C1', '소독약', 7000, 100);
INSERT INTO PRODUCT VALUES('A2', '마스크', 200, 100);
INSERT INTO PRODUCT VALUES('B2', '오징어', 5000, 100);
SELECT * FROM PRODUCT;

-- MEMBER

DROP SEQUENCE mCOUNT;

CREATE SEQUENCE mCOUNT
    START WITH      1
    INCREMENT BY    1
    MAXVALUE        100000
    MINVALUE        1
    NOCACHE
    NOCYCLE;
DELETE FROM MEMBER;
INSERT INTO MEMBER VALUES
    (mCOUNT.NEXTVAL, 'abc', '홍길동', '서울시 서대문구 대현동',
    'hong@hong.com', '010-9999-9999');
INSERT INTO MEMBER VALUES
    (mCOUNT.NEXTVAL, 'def', '김김동', '경기도 수원시',
    'kim@kim.com', '010-8888-8888');
SELECT * FROM MEMBER;

-- ORDERS
DROP SEQUENCE oNO;
DELETE FROM ORDERS;
CREATE SEQUENCE oNO
    START WITH      1
    INCREMENT BY    1
    MAXVALUE        3000
    MINVALUE        1
    NOCACHE
    CYCLE;

INSERT INTO ORDERS VALUES (TO_CHAR(SYSDATE,'RRMMDD')||TRIM(TO_CHAR(oNO.NEXTVAL,'000')),'abc',
                           TO_CHAR(SYSDATE, 'YYYY"년" MM"월" DD"일"'),'홍길동', '서울시 서대문수 대현동', '010-9999-9999');
INSERT INTO ORDERS VALUES (TO_CHAR(SYSDATE,'RRMMDD')||TRIM(TO_CHAR(oNO.NEXTVAL,'000')),'def',
                           TO_CHAR(SYSDATE, 'YYYY"년" MM"월" DD"일"'),'김김동', '경기도 수원시', '010-8888-8888');
INSERT INTO ORDERS VALUES (TO_CHAR(SYSDATE,'RRMMDD')||TRIM(TO_CHAR(oNO.NEXTVAL,'000')),'abc',
                           TO_CHAR(SYSDATE, 'YYYY"년" MM"월" DD"일"'),'홍아빠', '제주도 제주시', '010-7777-9999');
SELECT * FROM ORDERS;

-- ORDERDETAILS

DROP SEQUENCE odNO;
DELETE FROM ORDERDETAILS;
CREATE SEQUENCE odNO
    START WITH      1
    INCREMENT BY    1
    MAXVALUE        3000
    MINVALUE        1
    NOCACHE
    CYCLE;
INSERT INTO ORDERDETAILS VALUES (odNO.NEXTVAL, '230102001', 'A1',3000, 3);
INSERT INTO ORDERDETAILS VALUES (odNO.NEXTVAL, '230102001', 'B1',3000, 1);
INSERT INTO ORDERDETAILS VALUES (odNO.NEXTVAL, '230102002', 'A2',200, 20);
INSERT INTO ORDERDETAILS VALUES (odNO.NEXTVAL, '230102002', 'B2',500, 2);
INSERT INTO ORDERDETAILS VALUES (odNO.NEXTVAL, '230102002', 'C1', 7000, 1);
INSERT INTO ORDERDETAILS VALUES (odNO.NEXTVAL, '230102003', 'A1', 3000, 2);
INSERT INTO ORDERDETAILS VALUES (odNO.NEXTVAL, '230102003', 'B1', 3000, 1);
INSERT INTO ORDERDETAILS VALUES (odNO.NEXTVAL, '230102003', 'C1', 7000, 1);
SELECT *FROM ORDERDETAILS;

SELECT P.pCODE, pNAME, PRICE, QTY, (PRICE*QTY) COST
    FROM PRODUCT P, ORDERS O, ORDERDETAILS OD
    WHERE P.pCODE = OD.pCODE AND P.PRICE=OD.PRICE;