-- TABLE 삭제
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;

--TABLE 생성
-- MEMBER_LEVEL
CREATE TABLE MEMBER_LEVEL (
    LEVELNO     NUMBER(1)       PRIMARY KEY,
    LEVELNAME   VARCHAR2(12)    NOT NULL
);

SELECT * FROM MEMBER_LEVEL;
DESC MEMBER_LEVEL;

-- MEMBER
CREATE TABLE MEMBER (
    mNO     NUMBER(5)       PRIMARY KEY,
    mNAME   VARCHAR2(21)    NOT NULL,
    mPW     VARCHAR2(24)    CHECK(LENGTH(mPW)>=1 AND LENGTH(mPW)<=8),
    mEMAIL  VARCHAR2(60)    UNIQUE,
    mPOINT  NUMBER(6)       CHECK(mPOINT>=0),
    mRDATE  DATE            DEFAULT SYSDATE,
    LEVELNO NUMBER(1),
    FOREIGN KEY(LEVELNO) REFERENCES MEMBER_LEVEL(LEVELNO)
);
SELECT * FROM MEMBER;
DESC MEMBER;

-- DATA INSERT

-- MEMBER_LEVEL
INSERT INTO MEMBER_LEVEL VALUES(-1, 'black');
INSERT INTO MEMBER_LEVEL VALUES(0, '일반');
INSERT INTO MEMBER_LEVEL VALUES(1, '실버');
INSERT INTO MEMBER_LEVEL VALUES(2, '골드');
SELECT * FROM MEMBER_LEVEL;

-- MEMBER_MNO_SQ & MEMBER
DROP SEQUENCE MEMBER_MNO_SQ;
CREATE SEQUENCE MEMBER_MNO_SQ
    START WITH 1 
    INCREMENT BY 1 
    MAXVALUE 99999
    MINVALUE 1    
    NOCACHE
    NOCYCLE;

INSERT INTO MEMBER (mNO, mNAME, mPW, mEMAIL, mPOINT, mRDATE, LEVELNO)
    VALUES(MEMBER_MNO_SQ.NEXTVAL, '홍길동','aa','hong@hong.com',0 ,'22/03/10',0);
INSERT INTO MEMBER (mNO, mNAME, mPW, mEMAIL, mPOINT, mRDATE, LEVELNO)
    VALUES(MEMBER_MNO_SQ.NEXTVAL, '신길동','bb','sin@sin.com',1000 ,'22/04/01' ,1);
SELECT * FROM MEMBER;

-- 출력
SELECT mNO "mNO", mNAME "mNAME", TO_CHAR(mRDATE,'YYYY-MM-DD') "mRDATE", mEMAIL "mMAIL", mPOINT "point",
    LEVELNAME||'고객' "levelname"
    FROM MEMBER M, MEMBER_LEVEL L
    WHERE M.LEVELNO=L.LEVELNO;

    
    