-- TABLE 삭제
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;

--TABLE 생성
-- MEMBER_LEVEL
CREATE TABLE MEMBER_LEVEL (
    LEVELNO     NUMBER(1)       PRIMARY KEY,
    LEVELNAME   VARCHAR2(12)    NOT NULL
);

SELECT * FROM MEMBER_LEVEL;
DESC MEMBER_LEVEL;

-- MEMBER

CREATE TABLE MEMBER (
    mNO     NUMBER(5)       PRIMARY KEY,
    mNAME   VARCHAR2(21)    NOT NULL,
    mPW     VARCHAR2(24)    CHECK(mPW.LENGTH>=1 AND mPW.LENGTH<=8),
    mEMAIL  VARCHAR2(60)    UNIQUE,
    mPOINT  NUMBER(6)       CHECK(mPOINT>0),
    mRDATE  DATE            DEFAULT SYSDATE,
    LEVELNO NUMBER(1),
    FOREIGN KEY(LEVELNO) REFERENCES MEMBER_LEVEL(LEVELNO)
);

