-- 테이블 및 시퀀스 삭제
DROP TABLE PERSON;
DROP TABLE JOB;
DROP SEQUENCE pNO;
-- 테이블 및 시퀀스 생성
-- JOB
CREATE TABLE JOB (
    jNO     NUMBER(2,0)     PRIMARY KEY,
    jNAME   VARCHAR2(50)    NOT NULL
);
--PERSON
CREATE TABLE PERSON (
    pNO     NUMBER(5)       PRIMARY KEY,
    pNAME   VARCHAR2(50)    NOT NULL,
    jNO     NUMBER(2,0)     NOT NULL,
    KOR     NUMBER(3)       CHECK(KOR>=0) NOT NULL,
    ENG     NUMBER(3)       CHECK(ENG>=0) NOT NULL,    
    MAT     NUMBER(3)       CHECK(MAT>=0) NOT NULL,
    FOREIGN KEY (jNO) REFERENCES JOB(jNO)
);

SELECT * FROM JOB;
SELECT * FROM PERSON;
-- 더미데이터 INSERT (정우성 ~ 송혜교)
-- JOB
INSERT INTO JOB VALUES (10,'배우');
INSERT INTO JOB VALUES (20,'가수');
INSERT INTO JOB VALUES (30,'엠씨');
-- PERSON
CREATE SEQUENCE pNO
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999
    MINVALUE 1
    NOCACHE
    NOCYCLE;
INSERT INTO PERSON VALUES (pNO.NEXTVAL,'정우성', 10,90,80,81);
INSERT INTO PERSON VALUES (pNO.NEXTVAL,'박세영', 10,80,90,80);
INSERT INTO PERSON VALUES (pNO.NEXTVAL,'배수지', 20,20,90,90);
INSERT INTO PERSON VALUES (pNO.NEXTVAL,'설수현', 20,95,95,95);
INSERT INTO PERSON VALUES (pNO.NEXTVAL,'송혜교', 10,100,100,100);
SELECT * FROM JOB;
SELECT * FROM PERSON;
-- 기능별 QUERY 작성(1, 2, 3)
--1
INSERT INTO PERSON 
    VALUES (pNO.NEXTVAL,'홍길동', 
    (SELECT jNO FROM JOB WHERE jNAME='가수'),95,95,95);

--2  직업별 조회후 총점을 추가하여 총점이 높은 순으로 이름(번호)로 출력 없으면 없다고 출력
SELECT ROWNUM||'등' RN2,pNAME ,jNAME,KOR,ENG,MAT,TOTAL
    FROM (SELECT PNAME||'('||RN1||'번)' pNAME ,jNAME,KOR,ENG,MAT,TOTAL
        FROM (SELECT ROWNUM RN1, pNAME,jNAME,KOR,ENG,MAT,KOR+ENG+MAT TOTAL 
            FROM PERSON P, JOB J WHERE P.jNO = J.jNO) WHERE jNAME = '배우' ORDER BY TOTAL DESC)A; 
            
SELECT ROWNUM||'등' RN2,pNAME ,jNAME,KOR,ENG,MAT,TOTAL 
FROM (SELECT PNAME||'('||RN1||'번)' pNAME ,jNAME,KOR,ENG,MAT,TOTAL
FROM (SELECT ROWNUM RN1, pNAME,jNAME,KOR,ENG,MAT,KOR+ENG+MAT TOTAL
FROM PERSON P, JOB J WHERE P.jNO = J.jNO) WHERE jNAME = '배우' ORDER BY TOTAL DESC)A;
            

--3. 데이터베이스에 입력된 사람 전체를 조회 후 총점을 추가하여 총점이 높은 순으로 출력한다
SELECT ROWNUM||'등' RN2, A.* FROM (SELECT PNAME||'('||RN1||'번)' pNAME ,jNAME,KOR,ENG,MAT,TOTAL
    FROM (SELECT ROWNUM RN1, pNAME,jNAME,KOR,ENG,MAT,KOR+ENG+MAT TOTAL 
        FROM PERSON P, JOB J WHERE P.jNO = J.jNO) ORDER BY TOTAL DESC)A; 

-- SELECT jNAME FROM JOB

