-- EX1
INSERT INTO DEPT VALUES (50,'IT','SEOUL');
DELETE FROM DEPT WHERE DEPTNO=50;
COMMIT;
-- EX2
SELECT COUNT(*) CNT FROM DEPT WHERE DEPTNO=99;
INSERT INTO DEPT VALUES (50,'IT','SEOUL');
select * from dept;


--UPDATE
UPDATE DEPT SET DNAME='MARKETING', LOC='ANAYNG'
    WHERE DEPTNO=50;
    commit;
    
    
--DELETE
DELETE FROM DEPT WHERE DEPTNO=52;
rollback;
select * from dept;

