-- DROP & CREATE

DROP TABLE FRIEND;
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1  
    INCREMENT BY 1  
    MAXVALUE 1000  
    MINVALUE 1    
    NOCACHE
    NOCYCLE;
CREATE TABLE FRIEND(
    NO      NUMBER  PRIMARY KEY,
    NAME    VARCHAR2(30)    NOT NULL,
    TEL     VARCHAR2(30)    NOT NULL
);

-- 검색
SELECT * FROM FRIEND WHERE NAME LIKE '%'||'김'||'%' OR TEL LIKE '%'||'8'||'%';

SELECT COUNT(*) FROM FRIEND WHERE NAME='홍길동' AND TEL='010-9999-9999';
-- 추가

SELECT * FROM FRIEND