-- DROP & CREATE
DROP TABLE BOARD;
CREATE TABLE BOARD(
    NUM     NUMBER(5,0)     PRIMARY KEY,
    WRITER  VARCHAR2(30)    NOT NULL,
    SUBJECT VARCHAR2(100)   NOT NULL,
    CONTENT VARCHAR2(4000)  NOT NULL,
    EMAIL   VARCHAR2(30),
    READCOUNT   NUMBER(5,0) DEFAULT 0,
    PW      VARCHAR2(30)    NOT NULL,
    REF     NUMBER(5,0)     NOT NULL,
    RE_STEP NUMBER(3)       NOT NULL,
    RE_INDENT NUMBER(2)     NOT NULL,
    IP      VARCHAR2(30)    NOT NULL,
    RDATE   DATE            DEFAULT SYSDATE
);

SELECT * FROM BOARD;
-- 1. 글 갯수
SELECT COUNT(*) FROM BOARD;
-- 2. 글 목록(글 그룹이 최신인 글이 위로)
SELECT * FROM BOARD ORDER BY NUM DESC; --★★★★★★
-- 2. 글 목록(20개씩 topN)
SELECT * 
    FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOARD ORDER BY NUM DESC) A)
    WHERE RN BETWEEN 11 AND 20;   --★★★★★★
-- 2-2 답글 탑엔
SELECT * 
    FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOARD ORDER BY REF DESC, RE_STEP) A)
    WHERE RN BETWEEN 11 AND 20;
-- 3. 글쓰기(원글쓰기) 
    -- 글번호(글 갯수)
SELECT NVL(MAX(NUM),0)+1 FROM BOARD;
    -- 글번호,글쓴이 ,글제목, 글본문, EMAIL, PW
INSERT INTO BOARD 
            (NUM, WRITER, SUBJECT, CONTENT, EMAIL, PW, REF, RE_STEP, RE_INDENT, IP)
            VALUES
            ((SELECT NVL(MAX(NUM),0)+1 FROM BOARD), 'TEST1','제목1','본문1',NULL,'111',(SELECT NVL(MAX(NUM),0)+1 FROM BOARD),0,0,'192.169.0.1');

INSERT INTO BOARD 
            (NUM, WRITER, SUBJECT, CONTENT, EMAIL, PW, REF, RE_STEP, RE_INDENT, IP)
            VALUES
            ((SELECT NVL(MAX(NUM),0)+1 FROM BOARD), 'TEST2','제목2','본문2',NULL,'111',(SELECT NVL(MAX(NUM),0)+1 FROM BOARD),0,0,'192.169.0.1');
-- 4. 글번호로 글 상세보기(DTO) 내용 가져오기
SELECT * FROM BOARD WHERE NUM=1;

-- 5. 조회수 올리기
UPDATE BOARD SET READCOUNT = READCOUNT+1 WHERE NUM=1;

-- 6. 글 수정
UPDATE BOARD SET SUBJECT = '수정된 제목1',
                 CONTENT = '수정된 본문1',
                 EMAIL   = 'TEST1@TEST1.COM',
                 PW      = '111',
                 IP      = '127,0,0,1'
             WHERE NUM=1;
-- 7. 글 삭제
COMMIT;
DELETE FROM BOARD WHERE NUM=1 AND PW='111';
ROLLBACK;

-- 답변글
SELECT * FROM BOARD ORDER BY REF DESC, RE_STEP ASC;
-- 145번글(원글)
INSERT INTO BOARD (NUM, WRITER, SUBJECT, CONTENT, EMAIL, PW, REF, RE_STEP,RE_INDENT,IP)
            VALUES(145, '홍','원글1','본문',NULL,'111',145,0,0,'167,0,0,1');
--145의 1번째 답글달기
    -- 답변글 추가 전단계(엑셀의 ⓐ단계) 
UPDATE BOARD SET RE_STEP = RE_STEP+1 
    WHERE REF=145 AND RE_STEP>0; --8. 답변글 추가 전 단계 
    
    -- 답변글의 답글 추가 전단계(엑셀의 ⓐ단계 원글 REF:145 원글의 RE_STEP=2, 원글의 RE_INDENT=1)  
UPDATE BOARD SET RE_STEP = RE_STEP+1 
    WHERE REF=145 AND RE_STEP>2;
    -- 답변글 INSERT ( REF=145, RE_STEP = 1, RE_INDENT = 1)
INSERT INTO BOARD (NUM, WRITER, SUBJECT, CONTENT, EMAIL, PW, REF, RE_STEP,RE_INDENT,IP)
            VALUES(146, '홍','원글1-답1','본문','R@R.COM','111',145,1,1,'167,0,0,1');
    -- 답변글의 답변글 INSERT ( REF=145, RE_STEP = 1, RE_INDENT = 1)
INSERT INTO BOARD (NUM, WRITER, SUBJECT, CONTENT, EMAIL, PW, REF, RE_STEP,RE_INDENT,IP)
            VALUES(150, '김','원글1-답2-답1','본문','K@R.COM','111',145,3,2,'167,0,0,1');            
--145의 2번째 답글달기
INSERT INTO BOARD (NUM, WRITER, SUBJECT, CONTENT, EMAIL, PW, REF, RE_STEP,RE_INDENT,IP)
            VALUES(147, '김','원글1-답2','본문','K@R.COM','111',145,1,1,'167,0,0,1');
ROLLBACK;
---- test용 원글, 답변글            
INSERT INTO BOARD (NUM, WRITER, SUBJECT, CONTENT, EMAIL, PW, REF, RE_STEP,RE_INDENT,IP)
            VALUES(148, '박','원글2','본문',NULL,'111',148,0,0,'167,0,0,1');            
INSERT INTO BOARD (NUM, WRITER, SUBJECT, CONTENT, EMAIL, PW, REF, RE_STEP,RE_INDENT,IP)
            VALUES(149, '추','원글1-답3','본문','K@R.COM','111',145,1,1,'167,0,0,1');            
            
DELETE FROM BOARD WHERE RE_STEP=4;        
            

-- 답글의 답글 전단계       
UPDATE BOARD SET RE_STEP = RE_STEP+1 WHERE REF=145 AND RE_STEP>1;      
-- 답변글의 답변글 INSERT ( REF=145, RE_STEP = 1, RE_INDENT = 1)
INSERT INTO BOARD (NUM, WRITER, SUBJECT, CONTENT, EMAIL, PW, REF, RE_STEP,RE_INDENT,IP)
            VALUES((SELECT NVL(MAX(NUM),0)+1 FROM BOARD), '김','원글1-답2-답1','본문','K@R.COM','111',145,2,2,'167,0,0,1');   
            
            
            
            
   commit;         